In [25]:
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('spam.csv',encoding='latin-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [37]:
df.shape

(5572, 5)

In [39]:
#1. Data cleaning
#2. EDA
#3. Text Preprocessing
#4.Model building 
#5.Evaluation
#6. Improvement
#7. Website
#8.Deploy

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [43]:
# draw last 3 columns
df.drop(columns=['Unnamed: 2',	'Unnamed: 3',	'Unnamed: 4'],inplace=True)
df.sample(5)

        v1                                                 v2
5115  spam  Get 3 Lions England tone, reply lionm 4 mono o...
2145  spam  Sunshine Hols. To claim ur med holiday send a ...
2819  spam  INTERFLORA - åÒIt's not too late to order Inte...
761    ham  We are at grandmas. Oh dear, u still ill? I fe...
2481   ham                  K.:)do it at evening da:)urgent:)

In [45]:
# Renaming columns v1 and v2
df.rename(columns={'v1':'target','v2':'text'},inplace=True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [61]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [63]:
encoder.fit_transform(df['target'])

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [65]:
# missing values check
df.isnull().sum()

target    0
text      0
dtype: int64

In [67]:
#check for duplicate value
df.duplicated().sum()

403